services:
  ojdb:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - oj-postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oj_app
      POSTGRES_USER: oj_user
      POSTGRES_PASSWORD: oj_password
      POSTGRES_PORT: 5432
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - oj-redis-data:/data
    environment:
      REDIS_PORT: 6379
    networks:
      - backend

  api:
    build:
      context: ./
      target: api
    volumes:
      - ./migrations:/usr/local/app/migrations
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - worker
    develop:
      watch:
        - path: ./api
          action: sync
          target: /usr/local/app/api
        - path: ./shared
          action: rebuild
        - path: ./environment.yml
          action: rebuild
    networks:
      - backend

  worker:
    build:
      context: ./
      target: worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./migrations:/usr/local/app/migrations
      - ./dbconfig:/usr/local/app/dbconfig
    env_file:
      - .env
    depends_on:
      - ojdb
      - redis
    networks:
      - backend
    develop:
      watch:
        - path: ./worker
          action: sync
          target: /usr/local/app/worker
        - path: ./shared
          action: rebuild
        - path: ./environment.yml
          action: rebuild

networks:
  frontend:
  backend:


volumes:
  oj-postgresql-data:
  oj-redis-data:
